---
# Nxus version = nxos.7.0.3.I7.8

- name: ":::: NXOS file comparaison ::::"
  debug:
    msg: "NXOS tasks"

#- name: ":::: Configurable backup path ::::"
#  cisco.nxos.nxos_config:
#    backup: true
#    backup_options:
#      filename: backup.cfg
#      dir_path: /home/user

#- name: ":::: NXOS tasks  ::::"
#  cisco.nxos.nxos_snmp_server:
#    config:
#      aaa_user:
#        cache_timeout: 36000
#      communities:
#        - community: public
#          group: network-operator
#        - community: private
#          group: network-admin
#      contact: nxosswitchadmin@localhost
#      location: serverroom-1
#      traps:
#        aaa:
#          server_state_change: true
#        system:
#          clock_change_notification: true
#      hosts:
#        - host: 192.0.2.1
#          traps: true
#          version: '1'
#          community: public
#        - host: 192.0.2.1
#          source_interface: Ethernet1/1
#        - host: 192.0.2.2
#          informs: true
#          version: '3'
#          auth: NMS
#      users:
#        auth:
#          - user: snmp_user_1
#            group: network-operator
#            authentication:
#              algorithm: md5
#              password: '0x5632724fb8ac3699296af26281e1d0f1'
#              localized_key: true
#          - user: snmp_user_2
#            group: network-operator
#            authentication:
#              algorithm: md5
#              password: '0x5632724fb8ac3699296af26281e1d0f1'
#              localized_key: true
#              priv:
#                privacy_password: '0x5632724fb8ac3699296af26281e1d0f1'
#                aes_128: true
#        use_acls:
#          - user: snmp_user_1
#            ipv4: acl1
#            ipv6: acl2
#          - user: snmp_user_2
#            ipv4: acl3
#            ipv6: acl4

#- name: Merge the provided configuration with the existing running configuration
#  cisco.nxos.nxos_snmp_server:
#    config:
#      aaa_user:
#        cache_timeout: 36000
#      communities:
#        - community: public
#          group: network-operator
#        - community: private
#          group: network-admin
#      contact: nxosswitchadmin@localhost
#      location: serverroom-1
#      traps:
#        aaa:
#          server_state_change: true
#        system:
#          clock_change_notification: true
#      hosts:
#        - host: 192.0.2.1
#          traps: true
#          version: '1'
#          community: public
#        - host: 192.0.2.1
#          source_interface: Ethernet1/1
#        - host: 192.0.2.2
#          informs: true
#          version: '3'
#          auth: NMS
#      users:
#        auth:
#          - user: snmp_user_1
#            group: network-operator
#            authentication:
#              algorithm: md5
#              password: '0x5632724fb8ac3699296af26281e1d0f1'
#              localized_key: true
#          - user: snmp_user_2
#            group: network-operator
#            authentication:
#              algorithm: md5
#              password: '0x5632724fb8ac3699296af26281e1d0f1'
#              localized_key: true
#              priv:
#                privacy_password: '0x5632724fb8ac3699296af26281e1d0f1'
#                aes_128: true
#        use_acls:
#          - user: snmp_user_1
#            ipv4: acl1
#            ipv6: acl2
#          - user: snmp_user_2
#            ipv4: acl3
#            ipv6: acl4

## Not include

# - name: for idempotency, use full-form commands
#  cisco.nxos.nxos_config:
#    lines:
#      # - shut
#      - shutdown
#    # parents: int eth1/1
#    parents: interface Ethernet1/1