---
snmp_pollers:
  - name: "Entuity"
    snmpv3_user: "localsvc_snmp3_entuity"
    snmpv3_auth_password: "Authpassword"
    snmpv3_encryption_method: "AES-256"
    snmpv3_priv_password: "Privpassword"
    snmpv3_auth_method: "MD5"
    snmpv2c_community: “community-pwd”
...
